// Book Types

export const ADD_BOOK_STRUCT = 'ADD_BOOK_STRUCT';
export const DELETE_BOOK_STRUCT = 'DELETE_BOOK_STRUCT';
export const GET_BOOK_STRUCT_ALL = 'GET_BOOK_STRUCT_ALL';
export const BOOK_STRUCT_ERROR = 'BOOK_STRUCT_ERROR';

//Auth Types

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Alert Types

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Error Types

export const SET_ERRORS = 'SET_ERRORS';
export const REMOVE_ERROR = 'REMOVE ERRORS';

// METADATA SPEAKER ERRORS

export const ADD_SPEAKER = 'ADD_SPEAKER';
export const SPEAKER_ERROR = 'SPEAKER_ERROR';
export const GET_SPEAKER_ALL = 'GET_SPEAKER_ALL';
export const DELETE_SPEAKER = 'DELETE_SPEAKER';

// GET CURRENT METADATA ITEM

export const GET_CURRENT_ITEM = 'GET_CURRENT_ITEM';
export const GET_CURRENT_ITEM_ERROR = 'GET_CURRENT_ITEM_ERROR';
export const SET_CURRENT_ITEM_NULL = 'SET_CURRENT_ITEM_NULL';

// METADATA MEMBER PARTICIAPANTS

export const ADD_MEMBER = 'ADD_MEMBER';
export const MEMBER_ERROR = 'MEMBER_ERROR';
export const GET_MEMBER_ALL = 'GET_MEMBER_ALL';
export const DELETE_MEMBER = 'DELETE_MEMBER';

// Metadata Debate Title

export const ADD_DEBATE_TITLE = 'ADD_DEBATE_TITLE';
export const DEBATE_TITLE_ERROR = 'DEBATE_TITLE_ERROR';
export const GET_DEBATE_TITLE_ALL = 'GET_DEBATE_TITLE_ALL';
export const DELETE_DEBATE_TITLE = 'DELETE_DEBATE_TITLE';

// Metadata Ministries/Portfolio

export const ADD_PORTFOLIO = 'ADD_DEBATE_TITLE';
export const PORTFOLIO_ERROR = 'PORTFOLIO_ERROR';
export const GET_PORTFOLIO_ALL = 'GET_PORTFOLIO_ALL';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';

// Metadata Issues

export const ADD_ISSUES = 'ADD_ISSUES';
export const ISSUES_ERROR = 'ISSUES_ERROR';
export const GET_ISSUES_ALL = 'GET_ISSUES_ALL';
export const DELETE_ISSUES = 'DELETE_ISSUES';

// Metadata Tags

export const ADD_TAGS = 'ADD_TAGS';
export const TAGS_ERROR = 'TAGS_ERROR';
export const GET_TAGS_ALL = 'GET_TAGS_ALL';
export const DELETE_TAGS = 'DELETE_TAGS';

// GET CURRENT BOOK

export const GET_CURRENT_BOOK_STRUCTURE = 'GET_CURRENT_BOOK_STRUCTURE';
export const GET_CURRENT_BOOK_STRUCTURE_ERROR =
  'GET_CURRENT_BOOK_STRUCTURE_ERROR';

//Add Annexure's

export const GET_ANNEXURE_FOR_BOOK = 'GET_ANNEXURE_FOR_BOOK';
export const ANNEXURE_ERROR = 'ANNEXURE_ERROR';
export const DELETE_ANNEXURE_ID = 'DELETE_ANNEXURE_ID';
export const GET_CURRENT_ANNEXURE = 'GET_CURRENT_ANNEXURE';
export const CLEAR_CURRENT_ANNEXURE = 'CLEAR_CURRENT_ANNEXURE';

//Add Metadata Actions

export const GET_METADATA_FOR_BOOK = 'GET_METADATA_FOR_BOOK';
export const METADATA_ERROR = 'METADATA_ERROR';
export const DELETE_METADATA_ID = 'DELETE_METADATA_ID';
export const GET_CURRENT_METADATA = 'GET_CURRENT_METADATA';
export const CLEAR_CURRENT_METADATA_SECTION = 'CLEAR_CURRENT_METADATA_SECTION';

// Add Admin Users Actions

export const GET_ADMIN_USERS = 'GET_ADMIN_USERS';
export const POST_NEW_ADMIN_USERS = 'POST_NEW_ADMIN_USERS';
export const DELETE_NEW_ADMIN_USERS = 'DELETE_NEW_ADMIN_USERS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const REMOVE_USER_ERROR = 'REMOVE_USER_ERROR';
export const CLEAR_ADMIN_USERS = 'CLEAR_ADMIN_USERS';
export const GET_CURRENT_ADMIN_USERS = 'GET_CURRENT_ADMIN_USERS';
export const CLEAR_CURRENT_ADMIN_USERS = 'CLEAR_CURRENT_ADMIN_USERS';
export const REGISTER_ADMIN_SUCCESS = 'REGISTER_ADMIN_SUCCESS';

// Add User Log Data

export const GET_USER_LOGS = 'GET_USER_LOGS';
export const REMOVE_USER_LOGS = 'REMOVE_USER_LOGS';
